# Generated by Django 5.0.5 on 2024-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('NW', 'новость'), ('AR', 'статья')], default='NW', max_length=2),
        ),
    ]
